Dev
irvanti/Latihan pull request #23
Opened 2023-09-03 06:29 UTC by irvanti

2023-09-06 12:45 UTC, haydarmiezanie requested changes
please add notes and website that help you solve this query ( if exist )

2023-09-06 12:45 UTC, haydarmiezanie commented on 38-the-blunder.sql
> +select ceil(avg(salary) - avg(replace(salary, '0', '')))
please add notes what this query for

2023-09-08 13:50 UTC, haydarmiezanie approved these changes

2023-09-08 13:51 UTC, irvanti commented
thanks

2023-09-08 13:51 UTC, merged